/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/**
 *
 * @author Thinkpad E440
 */
public class chaoJDialog extends javax.swing.JDialog {
    Timer timer;
    int manRun = -40;
    int progressRun = 0;
    int i = 452;

    public chaoJDialog(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);

        initComponents();

        inIt();
 
         timer = new Timer(14, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (progressRun >= 1500) {
                    stop();
                    chaoJDialog.this.dispose();
                    
                } else {
                    lblDercorIcon.setLocation(manRun, 451);
                    progress.setValue(progressRun);
                    manRun += 3;
                    progressRun = progressRun + 7;
                    if (progressRun % 310 <= 150) {
                        i--;
                        lblDercorIcon.setLocation(manRun, i);
                    } else {
                        i++;
                        lblDercorIcon.setLocation(manRun, i);
                    }
                }
            }
        });
        timer.start();
    }
    public void  stop(){      
    timer.stop();                           
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        progress = new javax.swing.JProgressBar();
        lblDercorIcon = new javax.swing.JLabel();
        lblScreen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        progress.setMaximum(1490);
        jPanel1.add(progress, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 640, 20));

        lblDercorIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDercorIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/xxxxxxxxxxx.png"))); // NOI18N
        lblDercorIcon.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel1.add(lblDercorIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 50, 30));

        lblScreen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Chao.png"))); // NOI18N
        jPanel1.add(lblScreen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(chaoJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(chaoJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(chaoJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(chaoJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                chaoJDialog dialog = new chaoJDialog(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private void inIt() {
        setLocationRelativeTo(this);
        this.setTitle("Chào mừng đến với Neko Delivery");

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDercorIcon;
    private javax.swing.JLabel lblScreen;
    private javax.swing.JProgressBar progress;
    // End of variables declaration//GEN-END:variables
}
